title: Adrian Besleaga - Java Developer / Contractor / Freelancer
author:
  name: adrianweb
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  💻 Passionate WEB (AWS Certified) Developer with experience in: 
    Cloud (AWS), Microservices, JAVA, Spring Framework, Elasticsearch, Redis, Docker, ReactJs, DDD... .
show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-hacker

plugins:
 - jekyll-feed
 - jekyll-seo-tag
